default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: store_transactions_development

test:
  <<: *default
  database: store_transactions_test

production:
  <<: *default
  database: store_transactions_production

